### ISSUE TITLE
ref -  Application template role in Production install #3

### ISSUE THREAD

**Issue by telezoic** [DigitalNZ/supplejack_installation#6]
Thanks for looking into this @ostigley! [issue#3] 

I have pulled the master, and run this again. 

Barring one error, the template runs smoothly. The error is as follows 

    Seeding API data
       force    db/seeds.rb
        rake    db:seed --trace
    ** Invoke db:seed (first_time)
    ** Execute db:seed
    ** Invoke db:abort_if_pending_migrations (first_time)
    ** Invoke environment (first_time)
    ** Execute environment
    ** Invoke db:load_config (first_time)
    ** Execute db:load_config
    ** Execute db:abort_if_pending_migrations
    rake aborted!
    `Mongo::Error::NoServerAvailable: No server is available matching preference:     #<Mongo::ServerSelector::Primary:0x47014960171880 tag_sets=[] max_staleness=nil> using server_selection_timeout=30 and local_threshold=0.015`

I can confirm that mongo is running: 

    [bcdluser@eln-sj1 config]$ mongo
    MongoDB shell version v3.4.7
    connecting to: mongodb://127.0.0.1:27017
    MongoDB server version: 3.4.7

 I thought I might try and explicitly declare the mongoid host in `supplejack_api/spec/dummy/config/mongoid.yml`, to no avail

    development:
    clients:
    default:
      database: supplejack_api_development
      hosts:
        #<%= ENV['MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
    - 127.0.0.1:27017`

    strong:
      database: supplejack_api_development
      hosts:
        #<%= ENV['MONGOID_HOSTS'].gsub(/\s+/, "").split(',') %>
    - 127.0.0.1:27017`

I'm wondering if you have any suggestions about how to get around this . . . 

Thanks, 
D.

**Comment by ostigley** [comment]
Hi @telezoic, it looks like the problem is with the mongoid.yml as you point out.  I have simplified the file in the supplejack_api repo.  If you re pull master here and try again, it should be fixed now. 

Let me know how you get on.

**Comment by telezoic** [comment]
Thanks @ostigley I really appreciate you helping me with this!

I've incorporated your most recent changes, but I still get the error. I've been looking deeper into this, and added a `/data/db` folder to my server, now with `mongod` in the terminal I can see: 

```[bcdluser@eln-sj1 data]$ mongod
2018-01-23T12:48:37.162-0800 I CONTROL  [initandlisten] MongoDB starting : pid=2064 port=27017 dbpath=/data/db 64-bit host=eln-sj1.is.sfu.ca
2018-01-23T12:48:37.162-0800 I CONTROL  [initandlisten] db version v3.4.7
2018-01-23T12:48:37.162-0800 I CONTROL  [initandlisten] git version: cf38c1b8a0a8dca4a11737581beafef4fe120bcd
2018-01-23T12:48:37.162-0800 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
2018-01-23T12:48:37.162-0800 I CONTROL  [initandlisten] allocator: tcmalloc
2018-01-23T12:48:37.162-0800 I CONTROL  [initandlisten] modules: none
2018-01-23T12:48:37.163-0800 I CONTROL  [initandlisten] build environment:
2018-01-23T12:48:37.163-0800 I CONTROL  [initandlisten]     distmod: rhel70
2018-01-23T12:48:37.163-0800 I CONTROL  [initandlisten]     distarch: x86_64
2018-01-23T12:48:37.163-0800 I CONTROL  [initandlisten]     target_arch: x86_64
2018-01-23T12:48:37.163-0800 I CONTROL  [initandlisten] options: {}
2018-01-23T12:48:37.186-0800 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3395M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2018-01-23T12:48:37.290-0800 I CONTROL  [initandlisten] 
2018-01-23T12:48:37.290-0800 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-01-23T12:48:37.290-0800 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-01-23T12:48:37.290-0800 I CONTROL  [initandlisten] 
2018-01-23T12:48:37.291-0800 I CONTROL  [initandlisten] 
2018-01-23T12:48:37.291-0800 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2018-01-23T12:48:37.291-0800 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2018-01-23T12:48:37.291-0800 I CONTROL  [initandlisten] 
2018-01-23T12:48:37.291-0800 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2018-01-23T12:48:37.291-0800 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2018-01-23T12:48:37.291-0800 I CONTROL  [initandlisten] 
2018-01-23T12:48:37.420-0800 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2018-01-23T12:48:37.558-0800 I INDEX    [initandlisten] build index on: admin.system.version properties: { v: 2, key: { version: 1 }, name: "incompatible_with_version_32", ns: "admin.system.version" }
2018-01-23T12:48:37.558-0800 I INDEX    [initandlisten] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2018-01-23T12:48:37.577-0800 I INDEX    [initandlisten] build index done.  scanned 0 total records. 0 secs
2018-01-23T12:48:38.145-0800 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 3.4
2018-01-23T12:48:38.145-0800 I NETWORK  [thread1] waiting for connections on port 27017
2018-01-23T12:52:15.446-0800 I NETWORK  [thread1] connection accepted from 127.0.0.1:35456 #1 (1 connection now open)
2018-01-23T12:52:15.446-0800 I NETWORK  [thread1] connection accepted from 127.0.0.1:35458 #2 (2 connections now open)
2018-01-23T12:52:15.446-0800 I -        [conn1] end connection 127.0.0.1:35456 (2 connections now open)
2018-01-23T12:52:15.447-0800 I NETWORK  [conn2] received client metadata from 127.0.0.1:35458 conn2: { driver: { name: "mongo-ruby-driver", version: "2.4.3" }, os: { type: "linux", name: "linux-gnu", architecture: "x86_64" }, platform: "mongoid-6.2.1, 2.3.1, x86_64-linux, x86_64-pc-linux-gnu" }
2018-01-23T12:52:15.449-0800 I NETWORK  [thread1] connection accepted from 127.0.0.1:35460 #3 (2 connections now open)
2018-01-23T12:52:15.449-0800 I NETWORK  [conn3] received client metadata from 127.0.0.1:35460 conn3: { driver: { name: "mongo-ruby-driver", version: "2.4.3" }, os: { type: "linux", name: "linux-gnu", architecture: "x86_64" }, platform: "mongoid-6.2.1, 2.3.1, x86_64-linux, x86_64-pc-linux-gnu" }
2018-01-23T12:52:15.470-0800 I -        [conn3] end connection 127.0.0.1:35460 (2 connections now open)
2018-01-23T12:52:15.470-0800 I -        [conn2] end connection 127.0.0.1:35458 (1 connection now open)
```

It seems to me that mongo is indeed running, but it's failing to connect with supplejack_api. On a whim, I thought  I'd push through with the install to see what happened. Eventually I run `rails server` in the api folder (after all the steps at `http://digitalnz.github.io/supplejack/start/development-setup.html` Watching the output from this command I eventually console I get: 
```
MONGODB | Topology type 'unknown' initializing.
MONGODB | Server localhost:27017 initializing.
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
MONGODB | Address family not supported by protocol - connect(2) for [::1]:27017
Completed 500 Internal Server Error in 60017ms
  
Mongo::Error::NoServerAvailable (No server is available matching preference: #<Mongo::ServerSelector::Primary:0x69998409936300 tag_sets=[] max_staleness=nil> using server_selection_timeout=30 and local_threshold=0.015):
```

and that same `Mongo::Error:: . . . ` if I try and view the api through the api URL. 

Thanks again. And if you have nay further suggestions, that would be awesome . . .

D.

**Comment by ostigley** [comment]
Hi @telezoic, no problem at all, happy to help. 

There was a typo, so this one is all on me... can you try again?

I realised that I've been telling you to 'pull master' here... which is completely unnecessary.  You just need to run the command from the readme.  Hopefully that hasn't lead you astray, sorry:

`rails _5.1.4_ new mysupplejack_api_name --skip-bundle -m https://raw.github.com/digitalnz/supplejack_installation/master/supplejack_api_template.rb`

**Comment by telezoic** [comment]
Thanks again @ostigley!

With your latest changes, the Mongo error is gone, which is great. 

The same rake fails however, with a solr error.  The template output looks good at first: 
```
Attempting to start solr
       force    config/sunspot.yml
        rake    sunspot:solr:start
Creating directory /data/sites/supplejack_api/solr
Copying /home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sunspot_solr-2.2.7/solr/solr/solr.xml => /data/sites/supplejack_api/solr/solr.xml
Successfully started Solr ...
\nSleeping for 15 seconds because sunspot is can be slow to wake up in the morning... \n
Attempting to sidekiq
         run    bundle exec sidekiq > /dev/null 2>&1 & from "."
```
but then . . . 

```Seeding API data
       force    db/seeds.rb
        rake    db:seed --trace
** Invoke db:seed (first_time)
** Execute db:seed
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:abort_if_pending_migrations
rake aborted!
RSolr::Error::ConnectionRefused: Connection refused - {:data=>"[{\"id\":\"SupplejackApi::Record 5a68c0bb6ff821ef75f31e15\",\"type\":\"SupplejackApi::Record\",\"class_name\":\"SupplejackApi::Record\",\"internal_identifier_s\":\"abc123\",\"record_type_i\":\"0\",\"title_s\":\"Supplejack API\",\"description_s\":\"The Supplejack API is a mountable engine which provides functionality to store, index and retrieve metadata via an API.\",\"display_collection_s\":\"natlib.govt.nz\",\"category_sm\":\"engine\",\"title_text\":{\"boost\":10,\"value\":\"Supplejack API\"},\"description_text\":{\"boost\":2,\"value\":\"The Supplejack API is a mountable engine which provides functionality to store, index and retrieve metadata via an API.\"},\"display_collection_text\":\"natlib.govt.nz\"}]", :headers=>{"Content-Type"=>"application/json"}, :method=>:post, :params=>{:wt=>:json}, :query=>"wt=json", :path=>"update", :uri=>#<URI::HTTP http://127.0.0.1:8982/solr/development/update?wt=json>}
...
Caused by:
Faraday::ConnectionFailed: Failed to open TCP connection to 127.0.0.1:8982 (Connection refused - connect(2) for "127.0.0.1" port 8982)
```
I can see the sample record doesn't make it into solr. I continue with the install, thinking that I can run the seed later (after confirming solr and doing the sunspot upgrade. 
```
[bcdluser@eln-sj1 supplejack_api]$ bundle exec rake sunspot:solr:start
Successfully started Solr ...
```
looks good, but the reindex breaks: 

```
[bcdluser@eln-sj1 supplejack_api]$ bundle exec rake sunspot:solr:reindex
rake aborted!
NoMethodError: undefined method `fields' for nil:NilClass

/home/bcdluser/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/home/bcdluser/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => sunspot:solr:reindex => sunspot:reindex
(See full trace by running task with --trace)
```
and the api URL gives me: 
```
{
  "errors": [
    "Solr is temporarily unavailable please try again in a few seconds."
  ]
}
```

I though it might have a problem with my iptables but no (8982 & 8983 are wide open). Disclaimer: My experience with Solr is limited, especially in connection to rails. I was wondering if you had any nuggets of wisdom around this? 

Thanks, 
D.

**Comment by ostigley** [comment]
@motizuki might have some advice.  Solr can take along time to start sometimes.  We will try to increase the sleep time and see how that goes.

**Comment by motizuki** [comment]
@telezoic can you try to run this rake task instead?
`bundle exec rake sunspot:reindex[500,SupplejackApi::Record]`

**Comment by telezoic** [comment]
Thanks @motizuki 
I can!  Full trace below, gives me the nilClass error again

```
[bcdluser@eln-sj1 supplejack_api]$ bundle exec rake sunspot:solr:start
Removing stale PID file at /data/sites/supplejack_api/solr/pids/development/sunspot-solr-development.pid
Successfully started Solr ...
```



```
[bcdluser@eln-sj1 supplejack_api]$ bundle exec rake sunspot:reindex[500,SupplejackApi::Record] --trace
** Invoke sunspot:reindex (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute sunspot:reindex
rake aborted!
NoMethodError: undefined method `fields' for nil:NilClass
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/supplejack_api-4344cb44d987/app/models/supplejack_api/set_item.rb:14:in `<class:SetItem>'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/supplejack_api-4344cb44d987/app/models/supplejack_api/set_item.rb:11:in `<module:SupplejackApi>'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/supplejack_api-4344cb44d987/app/models/supplejack_api/set_item.rb:10:in `<top (required)>'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:476:in `load'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:476:in `block in load_file'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:661:in `new_constants_in'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:475:in `load_file'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:374:in `block in require_or_load'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `block in load_interlock'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:11:in `loading'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:36:in `load_interlock'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:357:in `require_or_load'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:335:in `depend_on'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:251:in `require_dependency'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/engine.rb:475:in `each'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/engine.rb:475:in `block in eager_load!'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/engine.rb:473:in `each'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/engine.rb:473:in `eager_load!'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sunspot_rails-2.2.7/lib/sunspot/rails/tasks.rb:34:in `block (4 levels) in <top (required)>'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sunspot_rails-2.2.7/lib/sunspot/rails/tasks.rb:34:in `each'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sunspot_rails-2.2.7/lib/sunspot/rails/tasks.rb:34:in `block (3 levels) in <top (required)>'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sunspot_rails-2.2.7/lib/sunspot/rails/tasks.rb:71:in `with_session'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sunspot_rails-2.2.7/lib/sunspot/rails/tasks.rb:19:in `block (2 levels) in <top (required)>'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/home/bcdluser/.rbenv/versions/2.3.1/bin/rake:23:in `load'
/home/bcdluser/.rbenv/versions/2.3.1/bin/rake:23:in `<top (required)>'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/home/bcdluser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/home/bcdluser/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/home/bcdluser/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => sunspot:reindex
```
Again, thanks for you assistance with this. 

D.

**Comment by motizuki** [comment]
@telezoic Let's try a different approach but manually indexing the records via Rails Console.

`bundle exec rails c`
`Sunspot.session = Sunspot::Rails.build_session`
`Sunspot.index!(SupplejackApi::Record.all)`

Let me know if that works.
Make sure you have Solr running on your machine before running this.

**Comment by ostigley** [comment]
@telezoic I have also updated this script so that the api seed task is paused until sunspot is responding to a curl request to `http://127.0.0.1:8982 `.  We think the problem is that the rake task fails because your sunspot does not boot in the 15 second sleep.   Hopefully this fix makes the install more friendly.  

If you can re run `rails _5.1.4_ new mysupplejack_api_name --skip-bundle -m https://raw.github.com/digitalnz/supplejack_installation/master/supplejack_api_template.rb`, hopefully you won't need @motizuki 's console commands.  If it still doesn't work, hopefully his commands fix the issue. 

Let us know, thanks.

**Comment by telezoic** [comment]
Thanks @ostigley & @motizuki! Sorry about the delay in this. 

When I run latest commit it repeats on the `Sleeping until sunspot is responsive...` I have to break the install process to get out of this. 

I was thinking maybe my environment was playing a role here, so in an effort to troubleshoot that I built a new one in vagrant and got the same message. 

I did some digging and I went back the previous commit (still in my new, vagrant environment), it still broke at the seed but after I installed the `java-1.7.0-openjdk-devel` I was able to start solr with

 `bundle exec rake sunspot:solr:run`.

I can re-index without issue now and see the seeded records in the solr admin console, and the api web interface. After doing the sunspot/solr upgrade I can now start solr with 
`bundle exec rake sunspot:solr:start` 
So that's great!

After adding the `capistrano` gem to each of the Gemfiles as per Ben's instructions, I've had to modify the manager and worker start up commands from the template 

`[vagrant@360-112-02a supplejack_manager]$ bundle exec rails s -b 0.0.0.0 -p 3001`

`[vagrant@360-112-02a supplejack_manager]$ bundle exec rails s -b 0.0.0.0 -p 3002` 

Which gets me all the pieces up and running. But in the manager my test harvests are failing at the preview stage. The preview stays blank and the status message is "initializing queue". In the sidekiq UI it looks like these efforts go straight to the 'critical queue' and I have to delete them.

If I run bundle exec sidekiq from the worker (not the manager as the docs tell me). The harvest preview works for source data, and harvested attributes, but the API preview  is blank and the status reads:  'Fetching final preview record from API...' 

I'm excited to be this far, and hoping you have some advice to take me past this :)

Thanks again,
D.

**Comment by ostigley** [comment]
Hi @telezoic 
in your api logs, can you see a post request starting with to `method=POST path=/harvester/records.json`, with a param `"preview"=>true`?  Is there any error following the request in the logs?

**Comment by motizuki** [comment]
@telezoic Would you be able to send us your `application.yml` file for the Worker and the Manager?

I will make a quick summary of all configuration and services you need to run in order to get the stack fully working on your computer:

Before starting any service make sure the `application.yml` files are configured correctly for the Worker and Manager.

These are the most important things you have to check, make sure URL and ports are correct, as well as the keys.

## WORKER `application.yml`

- `API_HOST: "http://127.0.0.1:4000"` Your API URL and port
- `API_MONGOID_HOSTS: "127.0.0.1:27017"` Mongo host and port
- `MANAGER_HOST: "http://127.0.0.1:4001"` You Manager host and port
- `WORKER_KEY: "workerkey"` this key needs to be exactly the same as the `WORKER_KEY` on the Manager `application.yml` file.
- `HARVESTER_API_KEY: "random string"` To find this key, open a `rails console` in your API project, and run `SupplejackApi::User.where(role: :harvester).first.authentication_token`. Let me know if you cannot find this user.

## MANAGER - `application.yml`

- `WORKER_HOST: http://127.0.0.1:4002` URL and port for your worker.
- `WORKER_KEY: workerkey` this key needs to be exactly the same as the `WORKER_KEY` on the worker `application.yml` file.
- `API_HOST: http://127.0.0.1:4000` URL and port for your API.
- `API_MONGOID_HOSTS: 127.0.0.1:27017` Mongo host and port
- `HARVESTER_API_KEY: "randon string"` To find this key, open a `rails console` in your API project, and run `SupplejackApi::User.where(role: :harvester).first.authentication_token`. Let me know if you cannot find this user.

## External services
- MongoDB
- Redis Server

## API
- `rails s --port 3000 -b 0.0.0.0`
- `bundle exec rake sunspot:solr:run`

## WORKER
- `rails s --port 3002 -b 0.0.0.0`
- `bundle exec sidekiq`

## MANAGER
- `rails s --port 3001`

Now you should be able to preview a record successfully.

Thanks

**Comment by telezoic** [comment]
Thanks again @ostigley & @motizuki!

My post request looks good:  `"preview"=>true,` without any errors.
```
Started POST "/harvester/records.json" for 127.0.0.1 at 2018-02-21 01:43:15 +0000
Processing by SupplejackApi::Harvester::RecordsController#create as JSON
Parameters: {"record"=>{"priority"=>0, "title"=>
["AIMING TO FULLY UNDERSTAND HOW WE HEAL: TREATMENT AND ASSESSMENT PROTOCOL DEVELOPMENT FOR CLINICAL RESEARCH ON PERFORMANCE-SPECIFIC SOCIAL ANXIETY DISORDER"],
 "display_content_partner"=>["Trinity Western University"], "category"=>["Dissertation/thesis"], 
"description"=>["Anxiety disorders—Treatment.", "Post-traumatic stress disorder.", "Psychic trauma.", "Stress management."], "internal_identifier"=>["oai:twu.arcabc.ca:twu_361"],
 "landing_url"=>["http://twu.arcabc.ca/islandora/object/twu%3A361"],
 "source_url"=>["http://twu.arcabc.ca/islandora/object/twu%3A361"],
 "source_id"=>"viudatasource"}, "required_fragments"=>[], "preview"=>true, "api_key"=>"3Us8ERUSPPThJx-Tz_xs"}
```

and my .ymls below: 

`/worker/config/application.yml`
```
development:
  API_HOST: "http://127.0.0.1:3000"
  API_MONGOID_HOSTS: "127.0.0.1:27017"/
  MANAGER_HOST: "http://127.0.0.1:3001"
  HARVESTER_CACHING_ENABLED: true
  AIRBRAKE_API_KEY: "abc123"
  LINK_CHECKING_ENABLED: "true"
  LINKCHECKER_RECIPIENTS: "test@example.com"
  HARVESTER_API_KEY: "3Us8ERUSPPThJx-Tz_xs"
  WORKER_KEY: "z7_Y91iyYyaBe5dv8yo6"
```
 `/manager/config/application.yml`

```
development: &development
  WORKER_HOST: "http://127.0.0.1:3002"
  WORKER_KEY: "z7_Y91iyYyaBe5dv8yo6"
  HARVESTER_API_KEY: "3Us8ERUSPPThJx-Tz_xs"
  HARVESTER_CACHING_ENABLED: true
  PARSER_TYPE_ENABLED: false
  API_HOST: "http://127.0.0.1:3000"
  API_MONGOID_HOSTS: "127.0.0.1:27017"

staging:
  <<:
```

I've upped my VM memory, on the off chance if might be playing a role here, to no avail. Still no API preview. But the really nice thing is that everything else is working, I have run several successful harvests and can see the results indexed into the api.  I might try this on another build and see if I can replicate the problem . . . :)

D.
